//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DxcGRE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class dashboard
    {
        public int Sno { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string BookingType { get; set; }
        [Required]
        public string RoomName { get; set; }
        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        [Required]

        public Nullable<System.DateTime> DateTo { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        public Nullable<System.DateTime> DateFrom { get; set; }
        public string BookingStatus { get; set; }
    }
}
