//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DxcGRE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class feedback
    {
        public int id { get; set; }
        public Nullable<int> Empid { get; set; }
        [Required]
        public string Usability { get; set; }
        [Required]
        public string Service { get; set; }
        [Required]
        public string User_Experience { get; set; }
        public string Comments { get; set; }
    }
}
